### PR TITLE
Windows 11 start button support

### PR DESCRIPTION
**Pull request by ge0rdi**
plus many small improvements

### CODE REVIEW

**Comment by ge0rdi** [comment]
@bonzibudd
@Gaurav-Original-ClassicShellTester
@XenHat 

Guys, any help with testing will be much appreciated 🙏 

I was working on this for some time and testes what I could (including on Win7/Win10).
It seems to be also compatible with ExplorerPatcher (but I'm not using the program so I did just some basic testing).

**Comment by ge0rdi** [comment]
@bonzibudd 
Hmm, weird. It seems to be working fine here.
Anyways, thank you :)

**Comment by bonzibudd** [comment]
@ge0rdi 
I just had a little while to test the new changes, everything that I’ve come across seems to be working as expected. I’m running Insider build 25252 for reference.

The menu positioning and the button integration seem to be working correctly, so I’m super happy about that. However, since around build 25217, the default Windows key is also overridden by the Win11 menu, so I think that will have to be fixed as well (I can provide more information if you think it’s worth diagnosing from an Insider build).

I appreciate the addition of the version # in the context menu :) I also like the transition to RRGGBB for the color palette. Do you know if this will affect existing installs that have custom colors, or is it a purely visual change?

For the skin changes, I didn’t find any issues with the skins I tested, but I will try some more when I have time. Maybe @CTVCAM8 can do some testing as well.

Thank you again for this!

**Comment by ge0rdi** [comment]
> However, since around build 25217, the default Windows key is also overridden by the Win11 menu, so I think that will have to be fixed as well (I can provide more information if you think it’s worth diagnosing from an Insider build).

I was focusing on standard Win11 22H2 build. But for sure would like to have a look at Insider as well.
I will install it to VM and try to have a look.

> Do you know if this will affect existing installs that have custom colors, or is it a purely visual change?

The intent is to change visual representation only (the way how it is presented in settings).
Original BBGGRR format will be still used internally. So it should be backward compatible.

**Comment by bonzibudd** [comment]
@ge0rdi 
So I've tested this a little bit more, and I noticed that the custom button images don't get rid of the Win11 button behind it. This doesn't have any functional problems but it looks strange with custom button images.
image
I thought you might already know about this, but just wanted to comment to confirm.

Also, I noticed that the "Windows 10 Settings" item is still present on Win11, so we can rename that (if the option is still applicable on Win11.) Or, maybe it would make more sense to move it to the "Controls" tab since it seems redundant to have a tab dedicated to only one option.
I re-discovered the issue #1164 and I'm going to add a log there. That seems like it could be an appropriate addition to this pull.

**Comment by ge0rdi** [comment]
> I noticed that the custom button images don't get rid of the Win11 button behind it

Yup, I know about this. It is unfortunate but I cannot do anything about it.
In Windows 11 the start button (and most likely whole taskbar) is handled by new XAML framework (I think that's the thing used for modern applications).
I have no clue how to tell it to not display some windows or so.
It is quite different from traditional windows subclassing and message hooking.

If anybody wants to use custom icon, it simply needs to cover the original button.
Also, it cannot contain completely transparent areas, as those will cause mouse clicks to go through. There has to be at least some minimal alpha value (which will still look transparent).

> Also, I noticed that the "Windows 10 Settings" item is still present on Win11, so we can rename that (if the option is still applicable on Win11.)

I cannot verify whether it works for Win11 as I don't have multi-monitor setup with Win11 at hand.
I guess I will leave this for now, until it will be clear if it makes sense on Win11 too.

> Or, maybe it would make more sense to move it to the "Controls" tab since it seems redundant to have a tab dedicated to only one option.

Yup. I agree that it looks weird to have separate tab with just one option.
But moving it will probably break existing setting.
Though I'm not sure how many people use this setting actually.

> I re-discovered the issue https://github.com/Open-Shell/Open-Shell-Menu/issues/1164 and I'm going to add a log there. That seems like it could be an appropriate addition to this pull.

Looks simple enough.
I will add fix for it.

**Comment by bonzibudd** [comment]
@ge0rdi 
I tried both of those new changes; they seem to be working as expected.
I found one issue with the Win11 button, it seems that Open-Shell menu and the right-click menu aren't accessible via touch screen. They do work with the custom start button enabled, though. Let me know if you would like me to attach any log file to diagnose this.

Other than that, I haven't found any other issues, but I might try ExplorerPatcher at some point to see if it has any issues, although I doubt it since it's based off of Windows 10 code.

**Comment by ge0rdi** [comment]
> I found one issue with the Win11 button, it seems that Open-Shell menu and the right-click menu aren't accessible via touch screen.

Yup, I guess that's expected (unfortunately).
What I did is to hook mouse events and _steal_ them so they won't reach the XAML framework (when in start button area).
But touch events are handled differently and I don't know how to hook those :(

I will need to get touch enabled device so that I can debug and play with it.
Until then I cannot do much about it, I guess :(

**Comment by ge0rdi** [comment]
@bonzibudd 
Please, create separate issues for outstanding problems (like the touch screen issue).

**Comment by Efreak** [comment]
> I will need to get touch enabled device so that I can debug and play with it.
> Until then I cannot do much about it, I guess :(

This works the same way when using Microsoft Remote Desktop on Android, if that helps. Just make sure it's set to use touch input and not virtual mouse.

**Pull request merged**
