### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by ge0rdi**
- New default Immersive skin for Win10/11 (#538) 
- Use proper modern settings icon (#495)
- Properly scale modern task icons (#518)

### CODE REVIEW

**Comment by bonzibudd** [comment]
Looks good from what I can see, I will do some testing later today. However I noticed that Open-Shell seems to override the default for the `user_name` option on the classic skins, and this works well on the Classic1 style but on Classic2 I would prefer it to be enabled by default. If there’s a way an exception can be added for the classic2 style that would be good.

The modern tasks and Settings icon look good so far.

**Comment by bonzibudd** [comment]
#162 and #262 are also related to the new theme.

**Comment by ge0rdi** [comment]
>  However I noticed that Open-Shell seems to override the default for the user_name option on the classic skins

Here is the change:
https://github.com/Open-Shell/Open-Shell-Menu/pull/1274/files#diff-82c43507e4ac2c77acac190d1f5ac373ebaf3c7365b3555967e7e708704aa631L5098-R5102

`options1` are default for classic skin, `options2` for two column and `options3` for win7 style.
What do you think should be proper defaults?

> The modern tasks and Settings icon look good so far.

Cool 👍

**Comment by bonzibudd** [comment]
The only thing that should be changed is that `USER_NAME` for options2 should be `1`. The other defaults look correct.

**Comment by ge0rdi** [comment]
> The only thing that should be changed is that USER_NAME for options2 should be 1.

Hmm, but originally the `USER_NAME` defaulted to `0`.
So you want to change that default for two column type, right?
I mean I have no problem with it. Just wanted to be sure (as it changes this for other skins too, but again no problem on my side).

**Comment by ge0rdi** [comment]
In fact, I think I will revert that change of `options1`, `options2`, `options3` defaults.
As it doesn't seem to be necessary (for Immersive skin). And for options not listed here we will pick defaults from actual skin definition.

So the only change there will be `USER_NAME=1` for `options2` if you'll confirm that you want to do this change (for all the skins).

**Comment by bonzibudd** [comment]
Actually, since my skin has `USER_NAME` set at 1, we should be able to get rid of that override too. That should be a better solution for the other skins.

However, we should still keep the `options1` overrides for `USER_IMAGE` and `USER_NAME` at `0`, as it makes more sense with the format of those skins. The skin files can't specify different defaults between the two classic styles, so that's why it is defined here.

**Comment by bonzibudd** [comment]
Looks good, I will test as soon as I can.

**Comment by bonzibudd** [comment]
Hey @ge0rdi, I've just found a potential crash with the Shutdown command on Windows 10, would you like me to attach info here or on a separate issue?

**Comment by ge0rdi** [comment]
I guess separate issue would be better. Or just team discussion?

**Comment by bonzibudd** [comment]
Everything looks good from what I can see. The skin seems to be loading fine in every configuration I tested. I tried the Settings icon in Win8.1 and several versions of 10, and it works well.

**Review by bonzibudd — APPROVED** [review]

**Pull request merged**
