### PR TITLE
update line 313 the download string

### PR DESCRIPTION
**Pull request by blackcrack**
Hi,

updatet at line 313 the IDS_VERSION_URL string to Github.
so far..

### CODE REVIEW

**Comment by ge0rdi** [comment]
What is the point of this change?
Auto updating simply doesn't work in current state. Changing URL of auto updater won't solve that.

**Comment by Ibuprophen** [comment]
@ge0rdi, for the time being, isn't there a way to simply just remove & add (or replace) it with the something like a URL/Link that will open the individuals browser to where the builds are for the individual to manually check for any updates? 

I'm just thinking about any temporary/permanent solutions to a broken Updater. 

This could, at least, keep the wolves at bay with submitting issues regarding this My Friend. 


~Ibuprophen

**Comment by ge0rdi** [comment]
Auto updater should update product automatically, imo.
If someone wants to update manually, he can easily go to github page and download installer.

Anyways, this is not related to actual PR.
And I vote for closing it as it doesn't bring any reasonable change.

**Comment by coddec** [comment]
For detecting the new version, we can put a text file in our gh-pages repository then use https://raw.githack.com/our_text_file_path in the program to get and compare version difference at the client end?

For automatic updating, I'm not sure if there is any existing open source solution or something.

Just giving some ideas, not sure if it's viable or not.

**Comment by blackcrack** [comment]
Hi @coddec ,

> 
> 
> For detecting the new version, we can put a text file in our gh-pages repository then use https://raw.githack.com/our_text_file_path in the program to get and compare version difference at the client end?
> 
> For automatic updating, I'm not sure if there is any existing open source solution or something.
> 
> Just giving some ideas, not sure if it's viable or not.

why not search in the subpath's and search the more higher number in version string
and download this file then..  well, i am not a programer but i know a bit what can work or not..

@coddec could you maybe not build a script where looks in the subdirectorys for a more higher
number in the files under the "version" string, tell a "More new File exist [download] and install it? [chancel] "  and download this file ? so a more enhanced updater where looks in the subfilesystem..

i have not the knowing about programming codec, you have it, you could set it up to multiple eventuality's over a webfs or something ...

is this not possible  ?

best regards
Blacky

**Comment by Ibuprophen** [comment]
@ge0rdi, I do understand the purpose for the Auto Updater and I'm not asking about removing this in its entirety. 

I was just thinking about something like hiding it (or similar) in the meantime until it's working and thus providing a (temporary) type of alternative for looking up updates in some way. 

It just seems to me (personally) that keeping/having a broken feature would/could ultimately be counter productive in one form or another (ie... Lowered Confidence in software, multiple/duplicate/repetitive issues submitted, etc...). 

I've encountered individuals (directly/indirectly both online & personally) who either doesn't have any experience with Github or very little experience with Github. This poses a unique challenge to those users who kinda feels like their in the dark. 

Thanks a Bunch! :-) 


~Ibuprophen

**Comment by ge0rdi** [comment]
Closing.
We can discuss updating possibilities elsewhere (either create an issue for it, or put it to project section).

**Pull request closed without merging**
