### PR TITLE
Don't change Taskbar text color/texture until relaunch

### LINKED ISSUE #602: Some settings under "Customize Taskbar" don't work properly until restart
**Describe the bug**
When you first enable Taskbar customization, using some options, like a taskbar texture, do not work fully until the Start Menu process is restarted.

**To Reproduce**
1. Enable Taskbar customization
2. Apply a custom texture
3. Click "OK" on Settings window
4. View improper Taskbar

**Expected behavior**
The settings should work instantly when you click "OK," or there should be a prompt that asks the user to restart the process before the program applies any changes.

**Screenshots**
This is what the taskbar may look like:
image

The texture works fine after the process is restarted.

**Version:**
 - Open-Shell: 4.4.162
 - OS: Windows 10 v2009

Edit: For clarification, the options affected are the text color and taskbar texture options.

### PR DESCRIPTION
**Pull request by bonzibudd**
This will accurately represent when these changes are able to take effect.

The behavior of Taskbar-related settings were changed to accommodate for programs like WindowBlinds, and it seems to have caused these two settings to not apply correctly. Currently, they don't make any immediate changes or are broken when applied, and this should fix that.

Fixes #602.

### CODE REVIEW

**Review by ge0rdi — APPROVED** [review]

**Comment by ge0rdi** [comment]
@bonzibudd 
There were no changes in installer AFAIK.

Setting that property used to be a problem on Windows 7 when symbolic name `System.AppUserModel.ToastActivatorCLSID` was used. That's why we are using GUID directly.
Not sure why system can have an issue with setting that.

What OS do you have?

Try to create log from installation by adding `/lvx* log.txt` to command line.
Maybe it will give us some clue.

**Comment by bonzibudd** [comment]
[log.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/6630349/log.txt)

This machine is Windows 21H1 build 19043.1023. It doesn't happen every time, but often enough that I think it may be an issue.

**Comment by ge0rdi** [comment]
There is this in log:
```
MSI (s) (30:F8) [03:03:38:702]: Executing op: ShortcutPropertyCreate(ShortcutName=5yrxep4d.upd|Open-Shell Update,PropertyKey={9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3}, 26,PropVariantValue={E407B70A-1FBD-4D5E-8822-231C69102472})
MSI (s) (30:F8) [03:03:38:702]: Note: 1: 1946 2: {9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3}, 26 3: Open-Shell Update.lnk 4: 32 
Warning 1946. Property '{9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3}, 26' for shortcut 'Open-Shell Update.lnk' could not be set. HRESULT 32.
```
The error should be `The process cannot access the file because it is being used by another process.` I guess (32 looks like standard Win32 API error code).

So maybe some other application has the file opened at that moment for whatever reason.
You can try to look for opened file using `Process Explorer` / `Process Hacker` tool.

**Comment by bonzibudd** [comment]
Ok, here's some information I got from Process explorer:
image
I don't know what could be the problem, but I did notice that there are a lot of "System" processes.

**Comment by ge0rdi** [comment]
You should look for `Open-Shell Update.lnk`.
Though it may happen that some process is holding that file just temporarily during installation.

For that you will need to use `Process Monitor` and check all file operations done during installation to see if somebody had that file opened (you can set filter with file name to see just relevant file ops).

Not sure what else to advise :(

**Comment by bonzibudd** [comment]
Ok, I think I got a log file of around the time that the warning appeared: [Logfile.PML](https://1drv.ms/u/s!AoOFyuzgg8P8fMLa9TJIJdg5uHM?e=pxwG9b)

It looks like there are a few processes altering the file in different ways, but I'm not exactly sure what to look for.

**Comment by ge0rdi** [comment]
There is `C:\Program Files\PowerToys\modules\launcher\PowerLauncher.exe` process opening the `.lnk` file for some reason.
This is definitely not something usually present on machines.

Try to end this application to see if it helps.

**Comment by bonzibudd** [comment]
Thanks for pointing this out. I have PowerToys on a lot of my systems, so that could definitely be a culprit. I will see if that makes a difference, and I'll point it out to the PowerToys team if that seems to be the main problem.

**Comment by bonzibudd** [comment]
Ok, I can't say for sure, but I haven't had any more errors so far after disabling PowerToys. I will report this to the PowerToys team. Thank you for your help with troubleshooting.

**Pull request merged**
