### PR TITLE
Use VS2019

### PR DESCRIPTION
**Pull request by ge0rdi**
Use latest VS for compilation.

### CODE REVIEW

**Comment by Ibuprophen** [comment]
This looks good to go on my end @ge0rdi. 

Would you prefer the others to review and merge or are you okay with my merging. 


~Ibuprophen

**Comment by ge0rdi** [comment]
@Ibuprophen 
I will merge it once approved (or after some time if there will be no activity from reviewers).

**Comment by Ibuprophen** [comment]
Not a problem My Friend! :-) 


~Ibuprophen

**Comment by blackcrack** [comment]
works in on Reactos/WinNT Server 2003 too  ?!?

**Comment by ge0rdi** [comment]
Current naming is inherited from `Classic-Shell` and I don't intend to change it.
Feel free to fill issue regarding the installer name. Maybe someone would like to change it.

**Comment by blackcrack** [comment]
Hi @ge0rdi :)

I do not have to change before the name, you have misunderstood me,
only the name of the file at AppVeyorBot builder a bit, if the possible exist to add a date YYYYMMDD
Open-Shell-%version%-%YYYYMMDD%-%release%.exe 
(and maybe add time)
Open-Shell-%version%-%YYYYMMDD%-HH:MM-%release%.exe
to have a distinction .

**Comment by ge0rdi** [comment]
I think the naming is fine as it is.
As I wrote I have no intention to change it.

**Comment by blackcrack** [comment]
> 
> 
> I think the naming is fine as it is.
> As I wrote I have no intention to change it.

pity.. so must i ever change the name by download :\\\\

**Comment by Ibuprophen** [comment]
@blackcrack, I don't believe that was what @ge0rdi was referring to... 

Although, Suggestions, Recommendations, Feedback, etc... are ALWAYS appreciated and encouraged, it's one of those determinations/decisions that's specific to prioritization. 

With there being certain items, areas, topics etc... that NEEDS to be addressed first before considering those "it would be nice to have..." that falls into the realm of "if it's not broken..." topics. 

This is where/why we always encourage member/user contributions by way of pull requests to review and take under consideration. 

Please don't be discouraged. This is a Free & Open Source Software that's being provided with the help of the community. 


~Ibuprophen

**Comment by blackcrack** [comment]
@Ibuprophen 
Hi Ibo, you can call me Blacky ;)
we could have a todo list, where stay's point for point what's the priory t have something to fellowing..
and to know what's the next step to know it's make sence to bring a new idea ..
best :)

**Comment by Ibuprophen** [comment]
@blackcrack, that isn't a bad idea as I've been pondering about this as well (unfortunately dragging my heels about it). 

There's a few ways to go about doing this and I've been eyeing the https://github.com/MrAlex94/Waterfox/issues/538 (as an example) that's being used for the Waterfox project. 

Just to add... This type of conversation is really quite a bit off topic on this specific pull request. 

When something has been decided upon, I'm sure you'll notice it pinned to the top of the list of Issues. 


~Ibuprophen

**Comment by blackcrack** [comment]
:| let us end this thinking about.. 
the important is, changing the url's to bring the peoples on this github pages
to make able to have peoples where can help on this project.. is this not done, have we are not manny peoples. 
We need Adversiting !! And this directly in the Program.. and not foreign links/urls where say's, this programm is not longer supportet.. and also if the a 2nd infoline--"but there goes further" <= This is bullshit.

In the Open shell must be all links fully fixed and soon as possible  a release with the right urls..
best regards
Blacky

**Comment by XenHat** [comment]
I disagree with this commit. This only makes use of the 142 toolset for VS2019.
**Why not update to 163?** The New compiler is much, much better.

**Comment by ge0rdi** [comment]
@XenHat 
> This only makes use of the 142 toolset for VS2019.

MSVC toolset v142 (v14.23) is latest one.

> Why not update to 163? The New compiler is much, much better.

You have probably mistaken this with VS version that is 16.3. But VS version (whole suite) and MSVC version (compiler) are different things.

**Comment by XenHat** [comment]
Quite possibly. The other projects I take care of refer to it as `163`. As long as it's whatever ships with VS2019 by default, all good <3

**Pull request merged**
