### PR TITLE
Update Start Menu style previews.

### PR DESCRIPTION
**Pull request by lixkote**
Update the old blurry start menu previews from classic shell days to a more modern pixel-perfect ones that resemble the new default immersive skin and the previews that Windows 10 gives in settings app.
obraz
obraz

### CODE REVIEW

**Comment by ge0rdi** [comment]
@bonzibudd 
Any thoughts on this?

**Comment by Darthagnon** [comment]
I vote nay; the Aero screenshots included by default beat oversimplified Metro screenshots proposed

**Review by bonzibudd — APPROVED** [review]
I think this looks great 👍

**Comment by Lixkote** [comment]
> I vote nay; the Aero screenshots included by default beat oversimplified Metro screenshots proposed. The sort of people installing Open/Classic Shell are looking to make Win10 look like Win7, so no reason to make it look more like Win10. The previews are also not "blurry". chrome_240210_03

I think personally, that my previews are still better than the old ones simply because;

1. Old previews are inaccurate, the default skin is not Windows 7's aero anymore, but its the Immersive skin which IS windows 10 styled, thus my previews provide an better visual representation of the actual default theme for the end user.
2. I feel open shell needs some modernization and improvements, and the previews were still from the classic shell's days, thus not reflecting the current features and changes.
3. From what i've seen most people(not tech oriented people, for example teachers in my school's computer lab) that use open shell use it for just the classic layout that they are used to, they don't really care about full theming the os to look like w7, and these who do, will be tech savy enough that new previews won't be any issue for them.

**Comment by ge0rdi** [comment]
Personally, I have no problem with existing previews, even if they are blurry and inaccurate (yup the menu looks differently by default).

But I agree that the point of these previews is to show how the menu style looks _schematically_.
I think it is good idea to have these previews skin-neutral (as users can use many different skins).

> The sort of people installing Open/Classic Shell are looking to make Win10 look like Win7, so no reason to make it look more like Win10.

I'd say there are many reasons why people install `Open-Shell`.
For sure they can customize it to resemble Win7 (or whatever else they are attached to).
But that is no reason to stick to some obsolete previews in settings.

**Comment by bynarie** [comment]
I like the new preview layout.. Looks more modern while still accomplishing the goal.

**Comment by Darthagnon** [comment]
I have used [Resource Hacker](https://angusj.com/resourcehacker/) to revert the preview images back to the good ones used previously, as I cannot stand the ugly new flat-design previews. I prefer a preview that actually shows what my Start menu will look like when applied, rather than some non-representative abstraction. For your convenience, please find attached:

1. Zip of the images extracted from Open Shell v4.4.191: [OpenShell good screenshot DLL images.zip](https://github.com/user-attachments/files/18725903/OpenShell.good.screenshot.DLL.images.zip)
2. Patched DLL for Open Shell v4.4.195: [StartMenuDLL_v4.4.195.zip](https://github.com/user-attachments/files/18725905/StartMenuDLL_v4.4.195.zip)

Would you guys be ok if I open a PR to revert this unfortunate change?

**Comment by ge0rdi** [comment]
> Would you guys be ok if I open a PR to revert this unfortunate change?

Nope.

The change was intentional and wanted.
As explained here https://github.com/Open-Shell/Open-Shell-Menu/discussions/2063#discussioncomment-11638092.

Feel free to use older `Open-Shell` version (or just your hacked version) if that's so important for you.

**Comment by Darthagnon** [comment]
From the Readme:
> A collection of utilities bringing back classic features to Windows.

This PR goes against the spirit of the project by adding non-classic Metro-styled previews to software that by default reverts Metro/Acrylic features to their Aero (or earlier) counterparts. The previews are also no longer representative of what the start menu will look like when the program is run.

**Comment by Darthagnon** [comment]
Here is the DLL for v4.4.198 with the screenshot previews reverted.
[StartMenuDLL_v4.4.198.zip](https://github.com/user-attachments/files/28220981/StartMenuDLL_v4.4.198.zip)

Checksum:
MD5: `2722ff7ec09902c2bc55ef62f9a3255e`

**Pull request merged**
