### PR TITLE
New artwork for Open-Shell

### PR DESCRIPTION
**Pull request by bonzibudd**
This adds the icon and additional artwork as discussed in #31.

### CODE REVIEW

**Comment by ge0rdi** [comment]
Looks good to me.

Just the rounded corner on install screen looks a bit odd (well, I'm not designer):
image

Win10/11 doesn't seem to use much rounded corners.

**Comment by ge0rdi** [comment]
One technical note.

Commits `Improve setup banner icon` and `Fix web.ico size` are basically fixups of earlier `New icons and installer artwork` (they just fix things introduced in that original commit).
It will be nice to squash them into original commit in the end.

You can do that easily using `git rebase -i origin/master` (you can search for _git interactive rebase_ if you are not familiar with it).

**Comment by bonzibudd** [comment]
@ge0rdi I made the changes, but I don't think I should have updated from open-shell-master as they are showing as new commits now. Let me know if I need to change anything from my end.

**Comment by ge0rdi** [comment]
Hmm, you should sync your master with `Open-Shell` repo.

First, make sure you have `upstream` set up, using this guide:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork

Then you should do:
`git fetch upstream`
`git rebase upstream/master`

This should end up with just your 2 commits on your master.
Then use `git push -f` to push that to your repo.

**Comment by ge0rdi** [comment]
It looks good now.

But `AppVeyor` is ignoring those changes because:
`Commit "e310e60a" of branch "master" skipped as commit files did not match "only_commits.files"`

I think it's because the last commit on your branch modifies just `readme.md` and we are not triggering builds on such changes.

Try to swap those commits (using `git rebase -i origin/master`).
So that the last commit on branch will change files in `Src` folder.

**Comment by bonzibudd** [comment]
Ok, I think it's fixed now. I'll do some spot-checking, but I think it's good to go.

**Comment by bonzibudd** [comment]
Update: I found a possible issue with the installer art. 

@ge0rdi I'd like to wait on pushing this for the moment.

**Comment by bonzibudd** [comment]
@ge0rdi 

Alright, everything looks fine now. I had made a silly mistake in the resolution of `Dialog2.jpg` but it should be correct now.

**Review by ge0rdi — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
