### PR TITLE
Updated URL's to ARPHELPLINK & ARPURLINFOABOUT

### PR DESCRIPTION
**Pull request by blackcrack**
Updated URL's to ARPHELPLINK & ARPURLINFOABOUT  strings

best 
Blacky

### CODE REVIEW

**Comment by blackcrack** [comment]
@ge0rdi 

what's now, is this blocked or should this be deleted or what ?
because it is still blocked, can anyone unblock this ? and the other request too ?
what's goes on ?
best 
Blacky

**Comment by ge0rdi** [comment]
@blackcrack 
You should update PR with requested changes.
I can approve it then.

Basically just fix commit message (`git commit --amend`) and then force push (`git push -f`).

**Comment by blackcrack** [comment]
Hi @ge0rdi 
i am not in linux and edit it directly in Github,
and i hace also not installed the github-client in windows, so, change it how you whant it and aprove it or delete it.. i need a decide and clean it up !

this is on the other one the same.. change it how you it need and approve it or remove it..

best regards
Blacky

**Comment by Ibuprophen** [comment]
@blackcrack & @ge0rdi, though, I agree that the changes to the link pointing to the Open Shell URL is a good idea but, just my opinion, it would also be great to continue using the Classic Shell Forum link (while it's still up) as a type of alternative location that some users (like myself) still use when the need arises. 

Since we're still building on various hints, tips, tricks, etc... The predecessors forum would only be a great tool to continue using, at least, for the time being. 

Any thoughts @coddec & @XenHat too??? 


~Ibuprophen

**Comment by blackcrack** [comment]
it is active administrate and moderating ? it's a bit back and forth, either it is open shell and an own Forum, because the users should do not get confused ..... I don't care if you change that .. it should be exist in the next couple years .. imho..

best

**Comment by ge0rdi** [comment]
I'd suggest to close this and rather create PR that will change all links to new locations (instead of just two links in installer).

**Comment by blackcrack** [comment]
if you do it, yes, do it now and not in sometime ..
the should have happened much earlier !
best regards
Blacky

**Pull request closed without merging**
