### PR TITLE
Modern settings support

### PR DESCRIPTION
**Pull request by ge0rdi**
Add support for modern settings searching on newer Win10 versions.

### CODE REVIEW

**Comment by Ibuprophen** [comment]
I apologize as I had a momentary laps of common sense... LOL! 

I did test it on Windows 8.1 Pro and it looks like it didn't affect that feature at all. 

What a weekend! LOL! :-) 


~Ibuprophen

**Comment by Gittyperson** [comment]
Thank you, Modern Settings search seems to work just fine. Only problem I noticed is that the Open-Shell-Menu is not re-enabled automatically. Had to go (on 2 PC's) in the Open Shell folder to manually open the Start Menu Settings shortcut. I updated from the 4_4_143-kslvasrf version.

Don't remember though, perhaps this was always the case with updates.

**Comment by ge0rdi** [comment]
@Gittyperson 
It should be started after upgrade automatically. Installer is supposed to start `StartMenu.exe` after successful installation.
Though I remember some reports that it doesn't behave that way.

I was never able to reproduce such issue :(

**Comment by Gittyperson** [comment]
Could it be related to the installation selections? Menu, Explorer, Update etc.? I've only enabled the Menu option.

**Comment by ge0rdi** [comment]
@Gittyperson 
It should be started when Start Menu feature is installed. But feel free to play with it a bit.
And report your eventual findings in separate issue (as it doesn't look to be connected to this PR).

**Comment by Gittyperson** [comment]
Ok, thanks. I wonder if you can make the Modern Settings search optional? Unless both default "Search for keywords" and "Match part of words" options are disabled, seems there's a lot of clutter in the search results now. Microsoft is to blame of course...

**Comment by ge0rdi** [comment]
Just untick `Settings` -> `Search Box` -> `Search Settings`.
The option was always there.

Though imo the naming is a bit misleading, because I was also thinking it is related to _settings_ (as machine settings), not _Settings_ (as Modern/Metro settings).
OTOH it kind of makes sense because Modern settings are opened by clicking on `Settings` button in Open-Shell start menu.

We can change the string to `Search modern settings` (or so). But this is unrelated to current PR.

> there's a lot of clutter in the search results now

I'm wondering what clutter are you referring to. Can you attach screenshot to show it?
Because the search seems to work fine for me, quite relevant settings are displayed.

**Comment by Gittyperson** [comment]
About clutter, I didn't mean it was a problem of the new feature implementation. It's just that partial search now returns a lot more results, most often useless. Example, when typing "inter" (to look a for a program staring with that) there are 22 Settings results and 37 Modern Settings results. This is with "Match parts of words" disabled.

Type "smart" and you'll get 1 Settings result and 4 Modern Settings results. I suspect there are so many Modern results, due to extended keywords/descriptions of the Modern Settings. Not a huge problem (correct results are still there), but it does change the look and feel of the Menu.

**Comment by ge0rdi** [comment]
Search uses keywords provided by MS for each setting.
So it will find those settings just as standard start menu would.

**Comment by anonimuos** [comment]
Works nicely. Thank you!

**Comment by ge0rdi** [comment]
@anonimuos 

Yup, I know about this.
For now I'm not sure how to solve it properly, so I didn't want to delay the feature.

**Comment by anonimuos** [comment]
Strangely enough on Windows 10 Version 2004, I have the original Classic Shell 4.3.1 installed and the Settings search is working flawlessly. But not in the interim releases (I run 1803 on my main "production" PC due to some unfixed bugs in 1809 and later) and there of course (after 1709 in fact, in all releases, the Settings search was broken).

**Comment by ge0rdi** [comment]
@anonimuos 
> Strangely enough on Windows 10 Version 2004, I have the original Classic Shell 4.3.1 installed and the Settings search is working flawlessly.

Is it clean installation, or could you have upgraded from some older Win10 version?

**Comment by XenHat** [comment]
I will test this as soon as I can, with the increasing reliance on modern
settings by Microsoft, I was forced to stop using OSM and I had no time to
implement it myself

**Comment by XenHat** [comment]
Code review looks good. Very interesting. Will stamp yay or nay after testing

**Comment by anonimuos** [comment]
> @anonimuos
> 
> > Strangely enough on Windows 10 Version 2004, I have the original Classic Shell 4.3.1 installed and the Settings search is working flawlessly.
> 
> Is it clean installation, or could you have upgraded from some older Win10 version?

I have upgraded from an older version so it has the *.settingcontent-ms files in place.

**Comment by ge0rdi** [comment]
@XenHat 
Thanks for review :)
I will keep this PR opened for a while to gather some more feedback.

@anonimuos 
> I have upgraded from an older version so it has the *.settingcontent-ms files in place.

Oki, so in that case those old files were searched. They may work but definitely they don't cover all settings in new Windows versions.
With build from this PR you should see more settings.

**Comment by anonimuos** [comment]
> Oki, so in that case those old files were searched. They may work but definitely they don't cover all settings in new Windows versions.
> With build from this PR you should see more settings.

Yes absolutely :) This is the right approach (shell namespace extension) as those settingcontent files are not even there in a clean install of a newer version, and not up-to-date for an upgrade install too.

**Pull request merged**
