### PR TITLE
Update Main.html

### PR DESCRIPTION
**Pull request by blackcrack**
remove the empty lines
and update url and versioning

### CODE REVIEW

**Comment by Ibuprophen** [comment]
Any thoughts @ge0rdi or @coddec? 


~Ibuprophen

**Comment by blackcrack** [comment]
@Ibuprophen  

8) => 4.4.139-suivthvv .. cool *s*

i have tomorrow free.. and in the next 2nd day have i nightshift, there want i test it :))))

best regards
Blacky

**Comment by blackcrack** [comment]
@Ibuprophen 
3-10 was a big hole, this couple messy lines have i removed..
this have changed the whole changes and have bring up the whole changed lines,
because.. a.E. i have changed the homepages http://www.classicshell.net/ => https://open-shell.github.io

this have give the changed lines of  15, 22, 34 if you look direktly
on this lines did i change nothing and must be comes out of removing  of the lines between 2-10..
what else can not it be, \*shrug*

best regards
Blacky

**Comment by Ibuprophen** [comment]
What do you think @coddec, @ge0rdi and/or @XenHat? 

Just looking for a 2nd+ Opinion... 

~Ibuprophen

**Pull request closed without merging**
